<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <script>
        // Promise是[异步编程]的一种解决方案，比传统的回调函数、事件更合理和更强大。
        // Promise对象有三种状态：pending（进行中）、resolved（已定型），resolved（已定型）又分为fulfilled（已成功）和rejected（已失败）
        // Promise对象的状态改变，只有两种可能：从pending变为fulfilled和从pending变为rejected
        // 只要这两种情况发生，状态就[凝固]了，不会再变了，会一直保持这个结果，这时就称为resolved（已定型）
        // 有了Promise对象，可以链式写异步，避免了[层层嵌套]的回调函数
        // 但还有更简洁的写法，就是async+promise

        // Promise对象是一个构造函数，用来生成Promise实例
        // Promise构造函数必须接受一个[函数]作为参数，否则报错，该函数的两个参数分别是resolve和reject函数
        // resolve和reject函数都允许传[一个参数]，供外部的then的resolve和reject函数里使用
        // 一旦新建Promise实例，它的函数参数就会[立即执行]
        // new Promise();// 报错
        const promise1 = new Promise(function (resolve, reject) {
            // console.log('This is Promise!!');
            if (false) {
                // resolve('resolve');// 执行resolve
            } else {
                // reject('reject');// 执行reject
            }
        });
        // console.log(promise1);

        // 可以在实例下then方法可以接受resolve、reject函数作为参数，传入promise
        // 也可以在then中传入resolve函数，在catch中传入reject函数（详情见promise实例下的方法文件）
        promise1.then(value => {
            console.log(value);// resolve
        }, error => {
            console.log(error);// reject
        });
        // 等同于
        promise1.then(value => {
            console.log(value);// resolve
        }).catch((error) => {
            console.log(error);// reject
        });

        // resolve与reject[不能同时执行，只能执行一个]，若已执行了其中一个，另一个便不再执行，取决于它们的先后
        // resolve与reject是在[本轮事件循环结束]时执行，总是[晚于本轮循环的其他同步任务]
        // 而setTimeout是在[下一轮事件循环开始]时执行，所以晚于resolve、reject
        // setTimeout(() => { console.log('setTimeout2') });
        const promise2 = new Promise(function (resolve, reject) {
            resolve('resolve');
            console.log(1);
            reject('reject');// 不执行
            console.log(2);
            setTimeout(() => { console.log('setTimeout1') });
        });
        promise2.then(value => {
            console.log(value);// resolve
        }).catch((error) => {
            console.log(error);// reject
        });

        // reject如果执行了，就必须有reject对应的函数传入，否则报错
        const promise3 = new Promise(function (resolve, reject) {
            // reject('reject');// 报错
        });



    </script>
</body>

</html>